apiVersion: v1
kind: Service
metadata:
  name: company-website-service
  namespace: company-website
spec:
  type: LoadBalancer
  selector:
    app: company-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000